# -*- coding: utf-8 -*-
"""semester_project_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ciNJ15GNx_7Ih7CJS2Ii_S6n3-_isyG3
"""

pip install streamlit

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Load your processed data
data = pd.read_csv("bls_data.csv") 

# Streamlit app layout
st.title('BLS Data Dashboard')

# Create a plot
fig, ax = plt.subplots(figsize=(12, 6))
for series_id in data["series_id"].unique():
    series_data = data[data["series_id"] == series_id]
    ax.plot(series_data["date"], series_data["value"], label=series_id)

ax.set_title('BLS Data')
ax.set_xlabel('Date')
ax.set_ylabel('Value')
ax.legend()
ax.grid(True)

st.pyplot(fig)

# Optionally display the raw data
st.subheader("Raw Data")
st.write(data)
